'use strict';
const knex = require('knex');
const Db2Client = require('../../src/client');

describe('DB2 Schema Compiler Unit Tests', () => {
  let db;

  beforeAll(() => {
    db = knex({ client: Db2Client, connection: {} });
  });
  afterAll(async () => {
    await db.destroy();
  });
  const getSqlStatements = (compiled) => compiled.map((entry) => entry.sql || entry);
  const compileColumn = (type, args, configure) => {
    const tableBuilder = db.client.tableBuilder('create', 'users', null, () => {});
    const tableCompiler = db.client.tableCompiler(tableBuilder);
    const columnBuilder = db.client.columnBuilder(tableBuilder, type, args);
    if (configure) configure(columnBuilder);
    return getSqlStatements(db.client.columnCompiler(tableCompiler, columnBuilder).toSQL());
  };

  describe('Column Compiler', () => {
    test('increments uses GENERATED ALWAYS identity syntax', () => {
      const statements = compileColumn('increments', ['id']);
      expect(statements.join(' ')).toContain('generated always as identity');
      expect(statements.join(' ')).not.toContain('generated by default');
    });
    test('bigIncrements uses BIGINT GENERATED ALWAYS identity syntax', () => {
      const statements = compileColumn('bigIncrements', ['id']);
      expect(statements.join(' ')).toContain('bigint not null generated always as identity');
    });
    test('decimal emits DECIMAL(p, s)', () => {
      const statements = compileColumn('decimal', ['amount', 8, 2]);
      expect(statements.join(' ')).toContain('decimal(8, 2)');
    });
    test('float emits FLOAT(p)', () => {
      const statements = compileColumn('float', ['ratio', 10]);
      expect(statements.join(' ')).toContain('float(10)');
    });
    test('double emits DOUBLE', () => {
      const statements = compileColumn('double', ['ratio']);
      expect(statements.join(' ')).toContain('double');
    });
    test('boolean emits SMALLINT with CHECK IN (0,1)', () => {
      const statements = compileColumn('boolean', ['enabled']);
      expect(statements.join(' ')).toContain('enabled smallint');
      expect(statements.join(' ')).toContain('check (enabled in (0,1))');
    });
    test('enu emits VARCHAR(max_len) with CHECK IN', () => {
      const statements = compileColumn('enu', ['status', ['a', 'bb', 'ccc']]);
      expect(statements.join(' ')).toContain('status varchar(3)');
      expect(statements.join(' ')).toContain("check (status in ('a','bb','ccc'))");
    });
    test('uuid emits CHAR(36) by default', () => {
      const statements = compileColumn('uuid', ['uuid_col']);
      expect(statements.join(' ')).toContain('uuid_col char(36)');
    });
    test('uuid supports binary uuid mode', () => {
      const statements = compileColumn('uuid', ['uuid_col', { useBinaryUuid: true }]);
      expect(statements.join(' ')).toContain('uuid_col binary(16)');
    });
    test('bigInteger alias emits BIGINT', () => {
      const statements = compileColumn('bigInteger', ['count']);
      expect(statements.join(' ')).toContain('count bigint');
    });
    test('text alias emits CLOB(32000)', () => {
      const statements = compileColumn('text', ['body']);
      expect(statements.join(' ')).toContain('body clob(32000)');
    });
    test('json alias emits CLOB(2M)', () => {
      const statements = compileColumn('json', ['payload']);
      expect(statements.join(' ')).toContain('payload clob(2m)');
    });
    test('comment emits COMMENT ON COLUMN as additional query', () => {
      const statements = compileColumn('text', ['body'], (column) => column.comment("Bob's note"));
      expect(statements.some((sql) => /COMMENT ON COLUMN users\.body IS 'Bob''s note'/i.test(sql))).toBe(true);
    });

    test('bigIncrements with primaryKey:false omits primary key', () => {
      const statements = compileColumn('bigIncrements', ['id', { primaryKey: false }]);
      expect(statements.join(' ')).toContain('bigint not null generated always as identity');
      expect(statements.join(' ')).not.toContain('primary key');
    });

    test('bigIncrements defaults to including primary key', () => {
      const statements = compileColumn('bigIncrements', ['id']);
      expect(statements.join(' ')).toContain('primary key');
    });

    test('timestamp({ useTz: true }) throws expected DB2 z/OS error', () => {
      expect(() => compileColumn('timestamp', ['created_at', { useTz: true }])).toThrow(
        'timestamp({ useTz: true }) is not supported for db2-zos'
      );
    });

    test('datetime() delegates to timestamp type', () => {
      const statements = compileColumn('datetime', ['created_at']);
      expect(statements.join(' ')).toContain('timestamp');
    });

    test('datetime({ useTz: false }) delegates to timestamp without throwing', () => {
      const statements = compileColumn('datetime', ['created_at', { useTz: false }]);
      expect(statements.join(' ')).toContain('timestamp');
    });
  });

  describe('Schema Compiler edge cases', () => {
    const withConnectionSettings = (settings, callback) => {
      const originalSettings = db.client.connectionSettings;
      db.client.connectionSettings = settings;
      try {
        callback();
      } finally {
        db.client.connectionSettings = originalSettings;
      }
    };

    test('dropTableIfExists throws with DB2-specific message', () => {
      const sc = db.client.schemaCompiler(db.schema);
      expect(() => sc.dropTableIfExists('users')).toThrow(
        'DROP TABLE IF EXISTS is not supported — use dropTable() and handle SQL0204N (object not found) in your application'
      );
    });

    test('createSchemaIfNotExists throws with DB2-specific message', () => {
      const sc = db.client.schemaCompiler(db.schema);
      expect(() => sc.createSchemaIfNotExists('MYSCHEMA')).toThrow(
        'CREATE SCHEMA IF NOT EXISTS is not supported — use createSchema() and handle errors in your application'
      );
    });

    test('dropSchemaIfExists throws with DB2-specific message', () => {
      const sc = db.client.schemaCompiler(db.schema);
      expect(() => sc.dropSchemaIfExists('MYSCHEMA')).toThrow(
        'DROP SCHEMA IF EXISTS is not supported — use dropSchema() and handle errors in your application'
      );
    });

    test('dropSchema with cascade=true emits CASCADE', () => {
      const sc = db.client.schemaCompiler(db.schema);
      sc.dropSchema('MYSCHEMA', true);
      expect(sc.sequence[0].sql).toBe('DROP SCHEMA MYSCHEMA CASCADE');
    });

    test('dropSchema with cascade=false emits RESTRICT', () => {
      const sc = db.client.schemaCompiler(db.schema);
      sc.dropSchema('MYSCHEMA', false);
      expect(sc.sequence[0].sql).toBe('DROP SCHEMA MYSCHEMA RESTRICT');
    });

    test('hasTable with schema includes creator binding', () => {
      withConnectionSettings({ currentSchema: 'MYSCHEMA' }, () => {
        const sc = db.client.schemaCompiler(db.schema);
        sc.hasTable('users');
        expect(sc.sequence[0].sql).toContain('AND CREATOR = ?');
        expect(sc.sequence[0].bindings).toEqual(['USERS', 'MYSCHEMA']);
      });
    });

    test('hasColumn with schema includes tbcreator binding', () => {
      withConnectionSettings({ currentSchema: 'MYSCHEMA' }, () => {
        const sc = db.client.schemaCompiler(db.schema);
        sc.hasColumn('users', 'email');
        expect(sc.sequence[0].sql).toContain('AND TBCREATOR = ?');
        expect(sc.sequence[0].bindings).toEqual(['USERS', 'EMAIL', 'MYSCHEMA']);
      });
    });
  });

  describe('Query Compiler columnInfo output parsing', () => {
    const withConnectionSettings = (settings, callback) => {
      const originalSettings = db.client.connectionSettings;
      db.client.connectionSettings = settings;
      try {
        callback();
      } finally {
        db.client.connectionSettings = originalSettings;
      }
    };

    const getColumnInfoQuery = (columnName) => db.table('users').columnInfo(columnName).toSQL();

    const namedRow = {
      NAME: 'ID',
      COLTYPE: 'INTEGER',
      LENGTH: 4,
      SCALE: 0,
      NULLS: 'N',
      DEFAULT: null,
    };

    test('named-key rows parse into column metadata map', () => {
      const compiled = getColumnInfoQuery();
      const cols = compiled.output([namedRow]);
      expect(cols.ID).toEqual({
        type: 'INTEGER',
        maxLength: 4,
        scale: 0,
        nullable: false,
        defaultValue: undefined,
      });
    });

    test('array-style rows parse into column metadata map', () => {
      const compiled = getColumnInfoQuery();
      const cols = compiled.output([['ID', 'INTEGER', 4, 0, 'N', null]]);
      expect(cols.ID.type).toBe('INTEGER');
      expect(cols.ID.nullable).toBe(false);
      expect(cols.ID.maxLength).toBe(4);
    });

    test('numeric string key rows parse into column metadata map', () => {
      const compiled = getColumnInfoQuery();
      const cols = compiled.output([{ 0: 'ID', 1: 'INTEGER', 2: 4, 3: 0, 4: 'N', 5: null }]);
      expect(cols.ID.type).toBe('INTEGER');
      expect(cols.ID.scale).toBe(0);
    });

    test('resp.rows wrapper format is handled', () => {
      const compiled = getColumnInfoQuery();
      const cols = compiled.output({ rows: [namedRow] });
      expect(cols.ID.type).toBe('INTEGER');
    });

    test('NULLS:Y maps to nullable:true', () => {
      const compiled = getColumnInfoQuery();
      const cols = compiled.output([{ ...namedRow, NULLS: 'Y' }]);
      expect(cols.ID.nullable).toBe(true);
    });

    test('DEFAULT values are preserved', () => {
      const compiled = getColumnInfoQuery();
      const cols = compiled.output([{ ...namedRow, DEFAULT: '42' }]);
      expect(cols.ID.defaultValue).toBe('42');
    });

    test('specific column lookup returns a single descriptor', () => {
      const compiled = getColumnInfoQuery('ID');
      const column = compiled.output([namedRow]);
      expect(column).toEqual({
        type: 'INTEGER',
        maxLength: 4,
        scale: 0,
        nullable: false,
        defaultValue: undefined,
      });
    });

    test('columnInfo with schema includes TBCREATOR binding', () => {
      withConnectionSettings({ currentSchema: 'MYSCHEMA' }, () => {
        const compiled = getColumnInfoQuery();
        expect(compiled.sql).toContain('AND TBCREATOR = ?');
        expect(compiled.bindings).toEqual(['USERS', 'MYSCHEMA']);
      });
    });
  });
});

describe('Db2SchemaCompiler', () => {
  let db;
  beforeAll(() => {
    const knex = require('knex');
    const Db2Client = require('../../src/client');
    db = knex({ client: Db2Client, connection: {} });
  });
  afterAll(() => db.destroy());
  test('hasTable() generates SYSIBM.SYSTABLES query with bound table name', () => {
    const sc = db.client.schemaCompiler(db.schema);
    sc.hasTable('MYTABLE');
    const q = sc.sequence[0];
    expect(q.sql).toContain('SYSIBM.SYSTABLES');
    expect(q.sql).toContain('?');
    expect(q.bindings[0]).toBe('MYTABLE');
  });
  test('hasTable() uppercases the table name', () => {
    const sc = db.client.schemaCompiler(db.schema);
    sc.hasTable('mytable');
    expect(sc.sequence[0].bindings[0]).toBe('MYTABLE');
  });
  test('hasColumn() generates SYSIBM.SYSCOLUMNS query with bound table+column', () => {
    const sc = db.client.schemaCompiler(db.schema);
    sc.hasColumn('MYTABLE', 'MYCOL');
    const q = sc.sequence[0];
    expect(q.sql).toContain('SYSIBM.SYSCOLUMNS');
    expect(q.bindings[0]).toBe('MYTABLE');
    expect(q.bindings[1]).toBe('MYCOL');
  });
  test('renameTable() emits RENAME TABLE old TO new', () => {
    const sc = db.client.schemaCompiler(db.schema);
    sc.renameTable('OLD', 'NEW');
    const stmt = sc.sequence[0];
    const sql = stmt.sql || stmt;
    expect(sql).toMatch(/RENAME TABLE OLD TO NEW/i);
  });
  test('createSchemaIfNotExists() throws — not supported on DB2 z/OS', () => {
    const sc = db.client.schemaCompiler(db.schema);
    expect(() => sc.createSchemaIfNotExists('MYSCHEMA')).toThrow('not supported');
  });
  test('dropTableIfExists() throws — not supported on DB2 z/OS', () => {
    const sc = db.client.schemaCompiler(db.schema);
    expect(() => sc.dropTableIfExists('MYTABLE')).toThrow('not supported');
  });
  test('dropSchemaIfExists() throws — not supported on DB2 z/OS', () => {
    const sc = db.client.schemaCompiler(db.schema);
    expect(() => sc.dropSchemaIfExists('MYSCHEMA')).toThrow('not supported');
  });
});
