const ColumnCompiler = require('knex/lib/schema/columncompiler');

class Db2ColumnCompiler extends ColumnCompiler {
  constructor(client, tableCompiler, columnBuilder) {
    super(client, tableCompiler, columnBuilder);
  }

  // DB2 specific column type mappings
  increments() {
    return 'integer generated by default as identity (start with 1, increment by 1) primary key';
  }

  bigIncrements() {
    return 'bigint generated by default as identity (start with 1, increment by 1) primary key';
  }

  varchar(length) {
    return length ? `varchar(${length})` : 'varchar(255)';
  }

  text() {
    return 'clob';
  }

  mediumtext() {
    return 'clob';
  }

  longtext() {
    return 'clob';
  }

  binary() {
    return 'blob';
  }

  timestamp() {
    return 'timestamp';
  }

  datetime() {
    return 'timestamp';
  }

  date() {
    return 'date';
  }

  time() {
    return 'time';
  }

  boolean() {
    return 'smallint';
  }

  json() {
    return 'clob';
  }

  uuid() {
    return 'char(36)';
  }
}

module.exports = { Db2ColumnCompiler };
